### ISSUE TITLE
Peer review 

### ISSUE THREAD

**Issue by hanrach** [STAT547-UBC-2019-20/group_3_mksm1228_sihaoyu1220#30]
## Data processing

- Data loading was done successfully. 

- You have multiple if statements in load_data.R, for reading in different files for different cities. Perhaps you could write a function called `read_write_city_data` and pass in the city name as the function param to avoid repetition.

- It's really cool how you combined the datasets into one in clean_data.R. I think there is some room for vectorization in this script as well when you are selecting useful variables.

## Data Analysis

- All the figures produced successfully.

- Nice use of functions in the EDA.R script. Perhaps the function names could have been more informative, instead of calling them plot1,2,3, etc.

- Number of listings by city is a helpful visualization to capture some main features of the data.

- `min_nights_vs_price.png` reminds me of our own plot where bunch of values are clustered at the bottom. Perhaps you can control the alpha to control the translucency of the points to emphasize density.

- Nice interpretation of the correlation plot that some predictor variables may be collinear, I did not think of that in my own analysis. 

- Overall the EDA was great, I think they are insightful and the visualizations are effective.

## Knitting

- I got some error when knitting the report: syntax error near unexpected token `newline' .

- Should provide `file_name` and `file_type` in your command in 
`Rscript Scripts/knitting_script.R --file_name=<file_name> --file_type=<file_type>`

**Comment by Sihaoyu1220** [comment]
Hi Rachel, thank you so much for your feedback! We will try to write a new function to avoid repetition in `load_data.R`, use vectorization in `clean_data.R`, and make changes on `min_nights_vs_price.png`. Also, the knitting part is all fixed in milestone 3! Thank you again for your feedback!
