### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by luckymeng7** [STAT547-UBC-2019-20/group_3_mksm1228_sihaoyu1220#45]
### Overview 
Overall, this project is well done up to this point! Analyzing the data related to Airbnb is an demanding topic as tourism industry has always played an important role in Canada. It would also benefit the host and traveler themselves if they understand the data better on the relationship between the price and the key parameters. The report has been well structured and enough insight has been given for the data.
	
### Instructions for usage
- The instruction for running the script is very clear and straight forward
- Output messages in the scripts are informative 
	
	
### Data import and clean
- Date imported successfully
- It's convenient to have different options in the argument to choose which province data to load. 
- `clean_data.R` is repeating the same functionality on the data for different province. You could try to vectorize this part to shorten the data cleaning time
	
### Data analysis and linear regression
- Well done in linear regression and data analysis
- For eda, it would be more informative if you could provide image name for the function output instead of plot1, plot2 etc...
- It is interesting to analysis the proportion of the the super host by city, it shows that the ratio of the super host is not linear related to the total host number.
- I agree on your analysis for the correlation diagram. If there are col-linearity problem, you should definitely need to drop the related variables before linear regression
	
### Report knitting and others
- The report is generated properly with the script
- The example script in `Readme` is not working directly with "copy-paste". I understand it meant to have either PDF or html for the `file_type`, but it would be easier to use if you have an argument option to generate both the output files all at once
- The images for the report could be re-sized to a better fit and it would be nice to add captions for the images

**Comment by Sihaoyu1220** [comment]
Hi Monica, thank you so much for your feedback! We will definitely use vectorization in `clean_data.R` and change function names for the EDA plots. Also, we have already fixed the image size and add captions in milestone 3. Thank you again for your feedback!
