### ISSUE TITLE
milestone 3 feedback?

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/group_3_mksm1228_sihaoyu1220#46]
Hello @yuliaUU @firasm ! 

@Sihaoyu1220 and I had a question regarding the feedback given for Milestone 3 and that is "```make all``` is absent." We are a little confused as to what this exactly means since the first line of our make file is ```all: Docs/Final_Report.html Docs/Final_Report.pdf``` and when we enter the ```make all``` command in the terminal, the reports generate for us. Could you please clarify what you meant so we can improve on it?

**Comment by yuliaUU** [comment]
It was my mistake!

**Comment by mksm1228** [comment]
Oh okay no problem! Could you also please consider the test functions we wrote?

**Comment by yuliaUU** [comment]
hi! I am not allowed to give more than 100% :( and you guys already got it
