### ISSUE TITLE
M5 Feedback

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group_3_mksm1228_sihaoyu1220#62]
Great app, I ran it without any issues! Very nice layout and presentation

Couple things to improve as a suggestion:
"play tab"
really needs a reset button 

Also, a lot of options produce empty plots;
![image](https://user-images.githubusercontent.com/54612866/78274006-6c715480-74c4-11ea-8a9b-a919f04be6d2.png)

Maybe you need a model to actually predict the values? so that the price won't stay NA and the whole graph is empty page?

Analysis tab:

Maybe add Price/day on the axes?
I would suggest converting the last graph to dropdown: you already have so many plots there

**Comment by mksm1228** [comment]
Hello Yulia,

Could you please clarify for us is the reset button supposed to make the plot return back to the default settings? Is this what you meant? 

Thanks!

**Comment by yuliaUU** [comment]
Yep, or clear the input. Either way. Cause once I chose the option that gave blank screen, it is hard to find option that produce some graph, so resetting to defaults will be nice!

**Comment by mksm1228** [comment]
Okay thanks Yulia, @Sihaoyu1220 and I will let you know if we have more questions!

**Comment by yuliaUU** [comment]
Did that work???

**Comment by mksm1228** [comment]
Yep that worked, thanks Yulia!
